[attachments]
mime_type_detect_buffer_size = 2048
mime_type_blacklist = [
    # PDFs (.pdf)
    "application/pdf",
    # Office (.doc, .docx, .xls, .xls, .ppt, .pptx, .odt, .ods, .odp)
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    # Skripte (.sh, .bat)
    "application/x-sh",
    "application/bat",
    "application/x-bat",
    "application/x-msdos-program"
]

[[guilds]]
# ID des Servers in dem der Bot arbeiten soll
id = 1234567890123456789
permitted_role_ids = [
    # IDs der Rollen im Server, die Reaction Roles hinzufügen können
    1234567890123456789
]
# ID des Channels im Server, in dem über gelöschte Nachrichten informiert wird
notification_channel_id = 1254153676784668742
